<?php

namespace Os\Framework\Http\Response;

class JsonResponse extends Response
{
    public function __construct(string|array $content = [], int $code = 200)
    {
        parent::__construct(is_array($content) ? json_encode($content) : $content, $code);
    }

    public function getContent(): string
    {
        return is_array($this->content) ? json_encode($this->content) : $this->content; // TODO: Change the autogenerated stub
    }

    /**
     * @param string|array $content
     */
    public function setContent(string|array $content): void
    {
        $this->content = is_array($content) ? json_encode($content) : $content;
    }
}